run:
  skip-dirs:
    - .github

linters-settings:
  gocyclo:
    min-complexity: 15
  gofmt:
    simplify: true
  misspell:
    locale: UK

linters:
  enable:
    - gofmt
    - gocyclo
    - misspell
  disable-all: false
  fast: false
  
